#include <iostream>
#include <memory>
#include <string>

#include <grpcpp/grpcpp.h>
#include "auth.grpc.pb.h" // Generated by CMake/Protobuf
#include "User.h"

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::Status;

// Namespaces generated from auth.proto
using auth::AuthService;
using auth::RegisterRequest;
using auth::RegisterResponse;
using auth::AuthRequest;
using auth::AuthResponse;

// Implementation of the gRPC Service
class AuthServiceImpl final : public AuthService::Service {
    
    // 1. REGISTER Endpoint
    Status Register(ServerContext* context, const RegisterRequest* request,
                    RegisterResponse* reply) override {
        
        std::string clientID = request->client_id();
        std::string pubKey   = request->public_key_hex();

        std::cout << "[gRPC] Received Register request for: " << clientID << std::endl;

        User newUser(clientID, pubKey);
        newUser.saveToDatabase();

        reply->set_success(true);
        reply->set_message("Client registered successfully.");
        
        return Status::OK;
    }

    // 2. AUTHENTICATE Endpoint
    Status Authenticate(ServerContext* context, const AuthRequest* request,
                        AuthResponse* reply) override {
        
        std::string clientID  = request->client_id();
        std::string message   = request->timestamp_message();
        std::string signature = request->signature_hex();

        std::cout << "[gRPC] Received Auth request for: " << clientID << std::endl;

        bool isValid = User::verifySignature(clientID, message, signature);

        if (isValid) {
            reply->set_authorized(true);
            reply->set_message("ACCESS GRANTED");
            std::cout << " -> Signature Valid. Access Granted." << std::endl;
        } else {
            reply->set_authorized(false);
            reply->set_message("ACCESS DENIED");
            std::cout << " -> Signature Invalid. Access Denied." << std::endl;
        }
        
        return Status::OK;
    }
};

void RunServer() {
    std::string server_address("0.0.0.0:50051");
    AuthServiceImpl service;

    ServerBuilder builder;
    // Listen on port 50051 without TLS (for local testing)
    builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());
    builder.RegisterService(&service);

    std::unique_ptr<Server> server(builder.BuildAndStart());
    std::cout << "------------------------------------------------" << std::endl;
    std::cout << "   gRPC Auth Server listening on " << server_address << std::endl;
    std::cout << "------------------------------------------------" << std::endl;

    server->Wait();
}

int main() {
    RunServer();
    return 0;
}